In [ ]:
# !pip install mygene

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import pickle
from sklearn.svm import NuSVR
from sklearn.model_selection import GridSearchCV
import mygene
import time

The input file raw_data_2samples.txt with gene expression data (CPM) is required to be in the .txt file format, with the first column containing Gene Symbols formatted in Hugo, Entrez, or Ensembl format. 

If the Gene Symbol is not in the Ensmbl Format, the active internet connection is required for the conversion of the gene format to Ensembl. 

The following columns should contain the patient sample.

The output file is a dataframe containg the stem cell class, Intra-Tumor Heterogenity (ITH), and frequency of immune cells, stem cells, and tumor cells.

In [2]:
def read_rna(file_path):

    rna = pd.read_csv(file_path, index_col=(0), sep='\t')
    rna.index = rna.index.astype(str)
    rna = rna.loc[~rna.index.duplicated(keep='first')]
    rna.dropna(axis=0, how='any', inplace=True)
    rna.dropna(axis=1, how='any', inplace=True)
    print('Sample file loaded')
    return rna

In [3]:
def read_sig(file_path):

    sig = pd.read_csv(file_path, index_col=(0))
    return sig

In [4]:
def cibersort(rna, sig, n_core=1):

    gridsearch = GridSearchCV(NuSVR(C=1.0, kernel='linear', max_iter=-1, shrinking=True),
                              cv=5, param_grid={"nu": [0.25, 0.5, 0.75]}, n_jobs= n_core,
                              scoring='neg_mean_squared_error', refit=True)
    gridsearch.fit(sig, rna)
    nu = gridsearch.best_params_['nu']

    clf = NuSVR(nu=nu, C=1.0, kernel='linear', max_iter=-1, shrinking=True, tol=1e-3)
    clf.fit(sig, rna)

    weights = np.array(clf.coef_)[0]
    weights[weights<0] = 0
    weights = weights / np.sum(weights)

    return weights

In [5]:
def cibersort_pipeline(rna, sig, n_core=1):

    common = list(set(rna.index) & set(sig.index))
    rna = rna[rna.index.isin(common)].sort_index()
    sig = sig[sig.index.isin(common)].sort_index()
    rna = stats.zscore(rna, axis=0, ddof=1)
    sig = stats.zscore(sig, axis=0, ddof=1)
    freq = pd.DataFrame(columns = rna.columns)
    freq['sample'] = sig.columns
    for patient in rna.columns:
        weights = cibersort(rna[patient], sig)
        freq[patient] = weights
    freq = freq.T
    print('Deconvolution done!')
    return freq

Citation for inter-tumour heterogenity

In [6]:
def ith(cancer):

    cancer = np.log2(cancer + 1)
    means = cancer.mean(axis=1).values
    z = (cancer.values - means[:, None])**2
    
    score = (np.sqrt(np.sum(z, axis=0) / (cancer.shape[0] - 1))).tolist()
    print('Inter-Sample Heterogenity calculated!')
    return score

In [7]:
def classification(model_path, rna):

    model_name = model_path
    model = pickle.load(open(model_name, 'rb'))
    feat = model.feature_names_in_
    rna = rna.loc[~rna.index.duplicated(keep='first')]
    rna = rna.T
    rna = rna.reindex(columns = feat, fill_value = 0).fillna(0)
    predictions=model.predict(rna)
    map_dict = {0: 'hESC', 1 : 'hMSC', 2 : 'hUSC', 3 : 'iPSC'}
    pred = [map_dict[element] for element in predictions]
    print('Classification Done!')
    return pred

In [8]:
def converter(rna, gene = None):

    mg = mygene.MyGeneInfo()
    if gene == 'Entrez':
        out = mg.querymany(rna.index, scopes='entrezgene', fields='ensembl.gene', species='human',
                           verbose = False, returnall=True, size=1)
        ensembl_list = []
        for i in out['out']:
            try:
                ensembl_list.append(i['ensembl']['gene'])
            except:
                ensembl_list.append('None')
        rna = rna.set_index(pd.Index(ensembl_list))
        rna = rna[rna.index != ('None')]
    elif gene == 'Hugo':
        out = mg.querymany(rna.index, scopes='symbol', fields='ensembl.gene', species='human',
                           verbose=False, returnall=True, size=1)
        ensembl_list = []
        for i in out["out"]:
            try:
                ensembl_list.append(i['ensembl']['gene'])
            except:
                ensembl_list.append('None')
        rna = rna.set_index(pd.Index(ensembl_list))
        rna = rna[rna.index != ('None')]
    elif gene == 'Ensembl':
        rna = rna
    else:
        rna = print('Please provide appropriate gene format name')
    return rna

In [9]:
def final_pipe(rna_path, sig_path, model_path, gene=None):
    rna = read_rna(rna_path)
    sig = read_sig(sig_path)
    rna = converter(rna, gene=gene)
    decon = cibersort_pipeline(rna, sig)
    ith1 = ith(rna)
    classification1 = classification(model_path, rna)
    data = decon
    data.columns = data.iloc[-1]
    data = data.iloc[:-1]
    data.insert(0, 'Class', classification1)
    data.insert(1, 'ITH', ith1)
    return data

In [14]:
tcga_rna_data_file = 'Data/Software_Data/raw_data_4samples.txt'
sig_mat_data_file = 'Data/Software_Data/sigmat.csv'
save_model_file = 'Data/Software_Data/svm_stemformatics.sav'

In [11]:
read_rna(tcga_rna_data_file)

Sample file loaded

                  Patient01   Patient02   Patient03    Patient04
ENSG00000121410    9.110265    1.570851    1.423439     0.627390
ENSG00000148584    0.031523    0.000000    0.000000     0.000000
ENSG00000166535  115.533290    1.145039    1.671930  1400.501095
ENSG00000175899  417.427293  910.018988  373.108842    64.557354
ENSG00000128274   58.633539   49.129347   26.500083    30.323835
...                     ...         ...         ...          ...
ENSG00000070476   37.449809   46.195183   28.610894    34.715563
ENSG00000203995    0.378281    0.000000    0.083596     0.209130
ENSG00000162378   21.435917  135.722951   37.095937    23.694417
ENSG00000074755   45.078473   76.145120   54.776592    81.163313
ENSG00000036549   18.346623   23.616438   23.156224    19.783688

[15939 rows x 4 columns]

In [12]:
'''
input: bulk RNA-Seq data,
        signature matrix,
        model,
        gene tyep: HUGO/ENSEMBLE/ENTREZ

output: stem cell class, Inter tumor heterogenity score (ITH), Deconvolution for immune cells, stem cells, tumor cells)
'''

begin = time.time()
data = final_pipe(tcga_rna_data_file, sig_mat_data_file, save_model_file, gene='Ensembl')
end = time.time()

Sample file loaded
Deconvolution done!
Inter-Sample Heterogenity calculated!
Classification Done!

/home/shreyansh/miniconda3/envs/research/lib/python3.10/site-packages/sklearn/base.py:288: UserWarning: Trying to unpickle estimator LinearSVC from version 1.2.1 when using version 1.2.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [13]:
data

sample,Class,ITH,T cells CD8,Monocytes,T cells CD4,NKT cells,B cells,NK cells,stem,PRAD,...,KIRC,OV,LAML,GBM,CESC,CHOL,LIHC,BRCA,MB,HNSC
Patient01,iPSC,0.979654,0.0,0.001463,0.0,0.01729,0.0,0.002049,0.025059,0.0,...,0.0,0.054984,0.00708,0.006136,0.170972,0.038075,0.0,0.0,0.0,0.159084
Patient02,hESC,0.998646,0.0,0.001354,0.0,0.022855,0.0,0.0,0.012363,0.0,...,0.0347,0.114174,0.0,0.0,0.014352,0.0,0.060137,0.028977,0.0,0.015636
Patient03,hUSC,0.908021,0.0,0.0,0.025749,0.021328,0.0,0.0,0.007306,0.004214,...,0.0,0.185689,0.003057,0.0,0.00527,0.0,0.046661,0.141256,0.0,0.090645
Patient04,hMSC,1.068543,0.0,0.011962,0.0,0.000642,0.0,0.005012,0.014589,0.0,...,0.0,0.037326,0.002027,0.0,0.617577,0.0,0.014855,0.017026,0.0,0.047116

In [41]:
print("Time taken to run the main function: ", end - begin)

Time taken to run the main function:  160.32901620864868