In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import pickle
from sklearn.svm import NuSVR
from sklearn.model_selection import GridSearchCV
from pygeneconverter import ensembl_to_hugo, hugo_to_ensembl
import time

The input file raw_data_4samples.txt with gene expression data (CPM) is required to be in the .txt file format, with the first column containing Gene Symbols formatted in Hugo, or Ensembl format. 

If the Gene Symbol is not in the Ensembl Format, we will convert it to ensembl. 

The following columns should contain the patient sample.

The output file is a dataframe containg the stem cell class, Intra-Tumor Heterogenity (ITH), and frequency of immune cells, stem cells, and tumor cells.

In [11]:
def read_rna(file_path):

    rna = pd.read_csv(file_path, index_col=(0), sep='\t')
    rna.index = rna.index.astype(str)
    rna = rna.loc[~rna.index.duplicated(keep='first')]
    rna.dropna(axis=0, how='any', inplace=True)
    rna.dropna(axis=1, how='any', inplace=True)
    rna = np.log2(rna+1)
    print('Sample file loaded')
    return rna

In [12]:
def read_sig(file_path):

    sig = pd.read_csv(file_path, index_col=(0))
    sig = np.log2(sig+1)
    return sig

In [13]:
rna_data_file = 'Data/Software_Data/raw_data_4samples.txt'
sig_mat_data_file = 'Data/Software_Data/sigmat.csv'
save_model_file = 'Data/Software_Data/svm_stemformatics.sav'

In [14]:
read_rna(rna_data_file)

Sample file loaded

                 Patient01  Patient02  Patient03  Patient04
ENSG00000121410   3.337749   1.362246   1.277056   0.702560
ENSG00000148584   0.044777   0.000000   0.000000   0.000000
ENSG00000166535   6.864598   1.101004   1.417882  10.452757
ENSG00000175899   8.708833   9.831337   8.547314   6.034686
ENSG00000128274   5.898052   5.647584   4.781364   4.969189
...                    ...        ...        ...        ...
ENSG00000070476   5.264905   5.560568   4.888056   5.158481
ENSG00000203995   0.462870   0.000000   0.115828   0.273969
ENSG00000162378   4.487738   7.095112   5.251565   4.626113
ENSG00000074755   5.526021   6.269503   5.801588   6.360422
ENSG00000036549   4.274010   4.621550   4.594323   4.377380

[15939 rows x 4 columns]

In [15]:
read_sig(sig_mat_data_file)

,B,CD4T,CD8Tex,CD8T,DC,Fibroblasts,Monocytes,Neutrophil,NK,Treg,...,OV,GBM,CESC,CHOL,LIHC,BRCA,MB,HNSC,MDSC,stem
ENSEMBL_ID,,,,,,,,,,,,,,,,,,,,,
ENSG00000176022,1.000000,1.000000,1.0,3.986629,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,5.993145,4.630624,1.000000,1.000000,1.000000,4.503394,1.000000,1.000000,3.580263,5.891353
ENSG00000131584,1.000000,1.000000,1.0,5.136626,1.000000,1.000000,5.856610,5.837552,5.799976,5.798538,...,4.939433,4.628245,1.000000,1.000000,6.078585,5.336864,6.173625,1.000000,3.819867,5.704451
ENSG00000169972,1.000000,7.280731,1.0,5.909584,6.160602,5.338564,1.000000,5.937397,1.000000,1.000000,...,5.158070,5.419515,5.613290,5.460873,6.209900,4.898034,6.214813,5.346464,3.967325,5.026639
ENSG00000162576,1.000000,1.000000,1.0,4.237569,1.000000,4.147146,1.000000,3.911857,1.000000,1.000000,...,6.338089,1.000000,1.000000,1.000000,3.680329,1.000000,5.721016,1.000000,4.076895,4.830165
ENSG00000160072,1.000000,1.000000,1.0,4.954262,1.000000,1.000000,1.000000,5.063577,1.000000,1.000000,...,7.169767,5.637809,1.000000,1.000000,5.882001,5.112439,1.000000,5.178187,4.225266,4.872257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000013563,1.000000,1.000000,1.0,4.051581,5.941806,5.896889,5.613555,4.788837,5.731228,5.518158,...,5.855049,1.000000,6.413071,1.000000,1.000000,5.983063,3.868464,5.419150,7.372872,5.392978
ENSG00000130827,1.000000,1.000000,1.0,4.081988,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,4.721286,1.000000,1.000000,1.000000,4.628323,1.000000,4.954483,3.969235,3.451058
ENSG00000126903,1.000000,1.000000,1.0,4.608146,5.892758,5.130386,6.237668,5.297388,5.857705,5.852690,...,6.329901,1.000000,4.863705,5.516042,6.425759,5.218935,4.033152,6.022321,3.583555,5.758758
ENSG00000130830,5.739978,3.438343,1.0,4.256623,5.795006,6.260474,6.724866,5.703007,6.271493,6.518162,...,4.529863,6.931828,4.009059,1.000000,6.161306,6.594322,5.759023,1.000000,6.690142,6.199189
ENSG00000185973,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,3.652816,4.734109,1.000000,1.000000,1.000000,1.000000,1.000000,4.824927,6.649451,5.067251

In [16]:
def deconvolution(rna, sig, n_core=-1):

    gridsearch = GridSearchCV(NuSVR(C=1.0, kernel='linear', max_iter=-1, shrinking=True),
                              cv=5, param_grid={"nu": [0.25, 0.5, 0.75]}, n_jobs= n_core,
                              scoring='neg_mean_squared_error', refit=True)
    gridsearch.fit(sig, rna)
    nu = gridsearch.best_params_['nu']

    clf = NuSVR(nu=nu, C=1.0, kernel='linear', max_iter=-1, shrinking=True, tol=1e-3)
    clf.fit(sig, rna)

    weights = np.array(clf.coef_)[0]
    weights[weights<0] = 0
    weights = weights / np.sum(weights)

    return weights

In [17]:
def deconv_pipeline(rna, sig):

    common = list(set(rna.index) & set(sig.index))
    rna = rna[rna.index.isin(common)].sort_index()
    sig = sig[sig.index.isin(common)].sort_index()
    rna = stats.zscore(rna, axis=0, ddof=1)
    sig = stats.zscore(sig, axis=0, ddof=1)
    freq = pd.DataFrame(columns = rna.columns)
    freq['sample'] = sig.columns
    for patient in rna.columns:
        weights = deconvolution(rna[patient], sig)
        freq[patient] = weights
    freq = freq.T
    print('Deconvolution done!')
    return freq

In [18]:
def ith(cancer):

    cancer = np.log2(cancer + 1)  
    means = cancer.mean(axis=1).values  # mean of each gene
    z = (cancer.values - means[:, None])**2 # (value - mean)**2
    
    score = (np.sqrt(np.sum(z, axis=0) / (cancer.shape[0] - 1))).tolist() # standard deviation within sample
    print('Inter-Sample Heterogenity calculated!')
    return score

In [19]:
def classification(model_path, rna):

    model_name = model_path
    model = pickle.load(open(model_name, 'rb'))
    feat = model.feature_names_in_
    rna = rna.loc[~rna.index.duplicated(keep='first')]
    rna = rna.T
    rna = rna.reindex(columns = feat, fill_value = 0).fillna(0)
    predictions=model.predict(rna)
    map_dict = {0: 'ECSC', 1 : 'MCSC', 2 : 'UCSC', 3 : 'iPCSC'}
    pred = [map_dict[element] for element in predictions]
    print('Classification Done!')
    return pred

In [20]:
def converter(rna, gene = None):
    if gene == 'Hugo':
        df = hugo_to_ensembl(rna.index)[['ENSEMBL_ID', 'HGNC_ID']].set_index('HGNC_ID')
        rna = pd.concat([df, rna], axis=1).dropna().set_index('ENSEMBL_ID')
    elif gene == 'Ensembl':
        rna = rna
    else:
        rna = print('Please provide appropriate gene format name')
    return rna

In [22]:
def final_pipe(rna_path, sig_path, model_path, gene=None):
    rna = read_rna(rna_path)
    sig = read_sig(sig_path)
    rna = converter(rna, gene=gene)
    decon = deconv_pipeline(rna, sig)
    ith1 = ith(rna)
    classification1 = classification(model_path, rna)
    data = decon
    data.columns = data.iloc[-1]
    data = data.iloc[:-1]
    data.insert(0, 'Class', classification1)
    data.insert(1, 'ITH', ith1)
    data.loc[data['stem'] == 0, 'Class'] = 'Differentiated'
    return data

In [23]:
'''
input: bulk RNA-Seq data,
        signature matrix,
        model,
        gene type: HUGO/ENSEMBL

output: stem cell class, Inter tumor heterogenity score (ITH), Deconvolution for immune cells, stem cells, tumor cells)
'''

begin = time.time()
data = final_pipe(rna_data_file, sig_mat_data_file, save_model_file, gene='Ensembl')
end = time.time()

Sample file loaded
Deconvolution done!
Inter-Sample Heterogenity calculated!
Classification Done!

/home/shreyansh/miniconda3/envs/research/lib/python3.12/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator LinearSVC from version 1.2.1 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [24]:
data

sample,Class,ITH,B,CD4T,CD8Tex,CD8T,DC,Fibroblasts,Monocytes,Neutrophil,...,OV,GBM,CESC,CHOL,LIHC,BRCA,MB,HNSC,MDSC,stem
Patient01,iPCSC,0.375640,0.0,0.0,0.0,0.008408,0.0,0.10362,0.243441,0.0,...,0.0,0.0,0.084148,0.039487,0.0,0.0,0.0,0.10993,0.063889,0.054382
Patient02,Differentiated,0.368141,0.0,0.0,0.0,0.0,0.0,0.1698,0.0,0.0,...,0.0,0.078388,0.029305,0.0,0.034766,0.101482,0.0,0.0,0.069944,0.0
Patient03,UCSC,0.339765,0.0,0.0,0.0,0.0,0.0,0.047734,0.140337,0.0,...,0.0,0.06195,0.0,0.0,0.033995,0.151905,0.0,0.067599,0.039993,0.018715
Patient04,iPCSC,0.426522,0.0,0.0,0.017604,0.058749,0.0,0.0,0.217032,0.0,...,0.0,0.0,0.162371,0.0,0.0,0.060284,0.0,0.16383,0.076461,0.035612

In [25]:
print("Time taken to run the main function: ", end - begin)

Time taken to run the main function:  12.447844743728638